# Creates cart Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable : 20
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: 834725375088.dkr.ecr.us-east-1.amazonaws.com/cart:503
        ports:
        - containerPort: 8080 
        envFrom: 
          - configMapRef:
                name: cart-configmap
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-configmap 
data:
  CATALOGUE_HOST: catalogue-svc
  REDIS_HOST: "roboshop-dev-redis.ij0ide.0001.use1.cache.amazonaws.com"
--- 
# This should be internal
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

--- 
# AutoScaling 
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cart-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75